/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 18 20:00:08 GMT 2026
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.TriangleClassifier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TriangleClassifier_ESTest extends TriangleClassifier_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(1241, 1, 1241);
      assertEquals(TriangleClassifier.TriangleType.ISOSCELES, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(1073741824, 1, 1073741824);
      //  // Unstable assertion: assertEquals(TriangleClassifier.TriangleType.RIGHT, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(1, 1, 1);
      assertEquals(TriangleClassifier.TriangleType.EQUILATERAL, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(2320, 2942, 2320);
      assertEquals(TriangleClassifier.TriangleType.ISOSCELES, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(2320, 1301, 2200);
      assertEquals(TriangleClassifier.TriangleType.SCALENE, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(1, 1, (-1685));
      assertEquals(TriangleClassifier.TriangleType.INVALID, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(201, (-782), 2569);
      assertEquals(TriangleClassifier.TriangleType.INVALID, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify(247, 2, 2320);
      assertEquals(TriangleClassifier.TriangleType.INVALID, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TriangleClassifier.TriangleType triangleClassifier_TriangleType0 = TriangleClassifier.classify((-1750), (-62), (-62));
      assertEquals(TriangleClassifier.TriangleType.INVALID, triangleClassifier_TriangleType0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      TriangleClassifier triangleClassifier0 = new TriangleClassifier();
  }
}
